### ISSUE TITLE
I had this problem when I was in 'make'

### ISSUE THREAD

**Issue by LLLLSilvia** [ccp-project/nimbus#3]
cargo +nightly build
   Compiling rustfft v1.0.1
error[E0277]: the trait bound `&{float}: Float` is not satisfied
   --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfft-1.0.1/src/lib.rs:38:36
    |
38  |                       .map(|phase| Complex::from_polar(&1.0, &phase))
    |                                    ^^^^^^^^^^^^^^^^^^^ the trait `Float` is not implemented for `&{float}`
    |
    = help: the following other types implement trait `Float`:
              f32
              f64
note: required by a bound in `Complex::<T>::from_polar`
   --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/num-complex-0.4.2/src/lib.rs:168:9
    |
168 | impl<T: Float> Complex<T> {
    |         ^^^^^ required by this bound in `Complex::<T>::from_polar`

error[E0308]: mismatched types
   --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfft-1.0.1/src/lib.rs:39:69
    |
39  |                       .map(|c| Complex {re: FromPrimitive::from_f32(c.re).unwrap(),
    |                                             ----------------------- ^^^^ expected `f32`, found `&f32`
    |                                             |
    |                                             arguments to this function are incorrect
    |
note: associated function defined here
   --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.15/src/cast.rs:505:8
    |
505 |     fn from_f32(n: f32) -> Option<Self> {
    |        ^^^^^^^^
help: consider dereferencing the borrow
    |
39  |                       .map(|c| Complex {re: FromPrimitive::from_f32(*c.re).unwrap(),
    |                                                                     +

error[E0308]: mismatched types
   --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfft-1.0.1/src/lib.rs:40:69
    |
40  | ...                   im: FromPrimitive::from_f32(c.im).unwrap()})
    |                           ----------------------- ^^^^ expected `f32`, found `&f32`
    |                           |
    |                           arguments to this function are incorrect
    |
note: associated function defined here
   --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.15/src/cast.rs:505:8
    |
505 |     fn from_f32(n: f32) -> Option<Self> {
    |        ^^^^^^^^
help: consider dereferencing the borrow
    |
40  |                                         im: FromPrimitive::from_f32(*c.im).unwrap()})
    |                                                                     +

error[E0277]: the trait bound `&_: Float` is not satisfied
   --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfft-1.0.1/src/lib.rs:137:27
    |
137 |             let twiddle = Complex::from_polar(&One::one(), &angle);
    |                           ^^^^^^^^^^^^^^^^^^^ the trait `Float` is not implemented for `&_`
    |
    = help: the following other types implement trait `Float`:
              f32
              f64
note: required by a bound in `Complex::<T>::from_polar`
   --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/num-complex-0.4.2/src/lib.rs:168:9
    |
168 | impl<T: Float> Complex<T> {
    |         ^^^^^ required by this bound in `Complex::<T>::from_polar`

error[E0369]: cannot multiply `Complex<&T>` by `Complex<T>`
   --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfft-1.0.1/src/lib.rs:138:33
    |
138 |             sum = sum + twiddle * x;
    |                         ------- ^ - Complex<T>
    |                         |
    |                         Complex<&T>
    |
help: consider introducing a `where` clause, but there might be an alternative better way to express this requirement
    |
130 | pub fn dft<T: Float>(signal: &[Complex<T>], spectrum: &mut [Complex<T>]) where Complex<&T>: Mul<Complex<T>> {
    |                                                                          ++++++++++++++++++++++++++++++++++

Some errors have detailed explanations: E0277, E0308, E0369.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `rustfft` due to 5 previous errors
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 101

**Comment by akshayknarayan** [comment]
This was a compilation issue in the rustfft dependency. It should be fixed in the default branch now.
